Update mp
pedrobcst/Xerus pull request #41
Opened 2022-11-28 01:04 UTC by qwe789qwec

Please Check

2022-11-28 01:16 UTC, pedrobcst commented
It seems that the newest versions of scipy have moved pinv2 used by peakutils somewhere else.

Can you fix the scipy version to 1.5.3 and see if the tests can pass?

2022-11-28 01:21 UTC, qwe789qwec commented
let me fix it later.
Why does it pass on my computer but not online?
what's different?

2022-11-28 01:24 UTC, pedrobcst commented on Xerus/queriers/multiquery.py
> -                   combination=False,
Why the combination was removed from CODQuery? Its by default True, and in this method we are doing it should always be False (messy code, I am sorry). Can you double check this?

2022-11-28 01:24 UTC, pedrobcst commented on tests/test_settings.py
> +# from pymatgen.ext.matproj import MPRester
Remove the old packages from comment. Not needed.

2022-11-28 01:25 UTC, pedrobcst commented on Xerus/queriers/mp.py
> +    if "pytest" in sys.modules:
Please explain why this is necessary

2022-11-28 01:25 UTC, qwe789qwec commented on Xerus/queriers/multiquery.py
> -                   combination=False,
I think I only change the mp part.
But let me check that later.

2022-11-28 01:30 UTC, pedrobcst requested changes
Please address the issues I raised, then it should be g2g.

Mostly check the COD querier again.
I have fixed for now scipy==1.5.3 since pinv2 moved somewhere else
Please explain those changes you made

2022-12-08 05:32 UTC, pedrobcst approved these changes

2022-12-08 05:44 UTC, merged